name: SnowzenResources
version: 1.0
author: snowzen
main: me.snowzen.snowzenresources.Main
load: STARTUP
api-version: 1.17.1

commands:
  hello:
    aliases: [hi]
    description: [this command says hello!]
  snowgive:
    aliases: [snowg]
    description: [gives you a custom item]