name: SnowzenResources
version: 1.0
author: snowzen
main: me.snowzen.snowzenresources.Main
api-version: 1.17
load: STARTUP

commands:
  hello:
    aliases: [hi]
    description: [this command says hello!]
  snowgive:
    aliases: [snowg]
    description: [gives you a custom item]
  snowspawn:
    aliases: [snows]
    description: [spawns a snowzen mob]
  ip:
    aliases: [getip]
    description: [Gets the current IP of the server]